/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    posts: Post;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'automotive-page': AutomotivePage;
    'branding-page': BrandingPage;
    navbar: Navbar;
    footer: Footer;
    'vision-cta': VisionCta;
    'contact-form': ContactForm;
    'contact-page': ContactPage;
    'blog-page': BlogPage;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'automotive-page': AutomotivePageSelect<false> | AutomotivePageSelect<true>;
    'branding-page': BrandingPageSelect<false> | BrandingPageSelect<true>;
    navbar: NavbarSelect<false> | NavbarSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'vision-cta': VisionCtaSelect<false> | VisionCtaSelect<true>;
    'contact-form': ContactFormSelect<false> | ContactFormSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  label: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  author?: string | null;
  category: number | Category;
  image: number | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: ('draft' | 'published') | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Override canonical URL if needed.
     */
    canonicalURL?: string | null;
    robots?: {
      noIndex?: boolean | null;
      noFollow?: boolean | null;
    };
    social?: {
      ogTitle?: string | null;
      ogDescription?: string | null;
      ogImage?: (number | null) | Media;
      twitterTitle?: string | null;
      twitterDescription?: string | null;
      twitterImage?: (number | null) | Media;
      twitterCard?: ('summary_large_image' | 'summary') | null;
    };
    schema?: {
      schemaType?:
        ('WebPage' | 'Article' | 'BlogPosting' | 'Service' | 'FAQPage' | 'MedicalOrganization' | 'Physician') | null;
      /**
       * Optional custom JSON-LD schema.
       */
      customSchema?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    /**
     * Comma separated keywords.
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Override canonical URL if needed.
     */
    canonicalURL?: string | null;
    robots?: {
      noIndex?: boolean | null;
      noFollow?: boolean | null;
    };
    social?: {
      ogTitle?: string | null;
      ogDescription?: string | null;
      ogImage?: (number | null) | Media;
      twitterTitle?: string | null;
      twitterDescription?: string | null;
      twitterImage?: (number | null) | Media;
      twitterCard?: ('summary_large_image' | 'summary') | null;
    };
    schema?: {
      schemaType?:
        ('WebPage' | 'Article' | 'BlogPosting' | 'Service' | 'FAQPage' | 'MedicalOrganization' | 'Physician') | null;
      /**
       * Optional custom JSON-LD schema.
       */
      customSchema?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    /**
     * Comma separated keywords.
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  category?: T;
  image?: T;
  excerpt?: T;
  content?: T;
  status?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        robots?:
          | T
          | {
              noIndex?: T;
              noFollow?: T;
            };
        social?:
          | T
          | {
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              twitterTitle?: T;
              twitterDescription?: T;
              twitterImage?: T;
              twitterCard?: T;
            };
        schema?:
          | T
          | {
              schemaType?: T;
              customSchema?: T;
            };
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        robots?:
          | T
          | {
              noIndex?: T;
              noFollow?: T;
            };
        social?:
          | T
          | {
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              twitterTitle?: T;
              twitterDescription?: T;
              twitterImage?: T;
              twitterCard?: T;
            };
        schema?:
          | T
          | {
              schemaType?: T;
              customSchema?: T;
            };
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    heroTitleLine1?: string | null;
    heroTitleHighlight?: string | null;
    heroCtaLabel?: string | null;
    heroCtaLink?: string | null;
    heroBackgroundImage?: (number | null) | Media;
    heroForegroundImage?: (number | null) | Media;
  };
  about?: {
    aboutHeading?: string | null;
    aboutHighlightText?: string | null;
    aboutBodyText?: string | null;
  };
  stats?:
    | {
        statValue: string;
        statLabel: string;
        id?: string | null;
      }[]
    | null;
  clients?: {
    clientsHeading?: string | null;
    clientLogos?:
      | {
          clientName: string;
          clientLogo?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  successStories?: {
    successHeading?: string | null;
    successViewMoreLabel?: string | null;
    successCtaLabel?: string | null;
    successCtaLink?: string | null;
    projects?:
      | {
          projectTitle: string;
          projectCategory: string;
          projectImage?: (number | null) | Media;
          projectLarge?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  services?: {
    servicesHeading?: string | null;
    serviceItems?:
      | {
          serviceTitle: string;
          serviceDescription: string;
          serviceImage?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  process?: {
    processHeading?: string | null;
    processSteps?:
      | {
          stepTitle: string;
          stepDescription: string;
          stepIcon?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  technologies?: {
    techHeading?: string | null;
    techDescription?: string | null;
    techCtaHeading?: string | null;
    techCtaLabel?: string | null;
    techCtaLink?: string | null;
    techIcons?:
      | {
          /**
           * Used as fallback filename if no custom logo uploaded (e.g. /images/tech/react.svg)
           */
          techName: string;
          /**
           * Upload a custom logo — overrides the default icon
           */
          techLogo?: (number | null) | Media;
          /**
           * Horizontal position (desktop layout)
           */
          techX?: number | null;
          /**
           * Vertical position (desktop layout)
           */
          techY?: number | null;
          /**
           * Icon size in px
           */
          techSize?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  testimonials?: {
    testimonialsHeading1?: string | null;
    testimonialsHeading2?: string | null;
    testimonialItems?:
      | {
          testimonialName: string;
          testimonialReview: string;
          testimonialRating?: number | null;
          testimonialAvatar?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  industries?: {
    industriesHeading?: string | null;
    industriesDescription?: string | null;
    industryItems?:
      | {
          industryTitle: string;
          industryDescription: string;
          industryIcon?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  latestInsights?: {
    insightsHeading?: string | null;
    insightsCtaLabel?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Override canonical URL if needed.
     */
    canonicalURL?: string | null;
    robots?: {
      noIndex?: boolean | null;
      noFollow?: boolean | null;
    };
    social?: {
      ogTitle?: string | null;
      ogDescription?: string | null;
      ogImage?: (number | null) | Media;
      twitterTitle?: string | null;
      twitterDescription?: string | null;
      twitterImage?: (number | null) | Media;
      twitterCard?: ('summary_large_image' | 'summary') | null;
    };
    schema?: {
      schemaType?:
        ('WebPage' | 'Article' | 'BlogPosting' | 'Service' | 'FAQPage' | 'MedicalOrganization' | 'Physician') | null;
      /**
       * Optional custom JSON-LD schema.
       */
      customSchema?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    /**
     * Comma separated keywords.
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "automotive-page".
 */
export interface AutomotivePage {
  id: number;
  autoHero?: {
    autoHeroBadgeLabel?: string | null;
    autoHeroTitleLine1?: string | null;
    autoHeroTitleHighlight?: string | null;
    autoHeroDescription?: string | null;
    autoHeroCtaLabel?: string | null;
    autoHeroCtaLink?: string | null;
    autoHeroImage?: (number | null) | Media;
    autoHeroStats?:
      | {
          autoStatValue: string;
          autoStatLabel: string;
          id?: string | null;
        }[]
      | null;
  };
  autoSolutions?: {
    autoSolutionsTitle?: string | null;
    autoSolutionsHighlight?: string | null;
    autoSolutionsItems?:
      | {
          autoSolutionNumber: string;
          autoSolutionTitle: string;
          autoSolutionDescription: string;
          autoSolutionFeatures?:
            | {
                featureText: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  autoWhyChooseUs?: {
    autoWhyTitle?: string | null;
    autoWhyItems?:
      | {
          whyTitle: string;
          whyIcon?: ('UserRound' | 'Cog' | 'ShieldCheck' | 'ClipboardCheck' | 'LayoutDashboard' | 'Megaphone') | null;
          whyDescription: string;
          id?: string | null;
        }[]
      | null;
  };
  autoFaq?: {
    autoFaqHeading?: string | null;
    autoFaqItems?:
      | {
          faqQuestion: string;
          faqAnswer: string;
          id?: string | null;
        }[]
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Override canonical URL if needed.
     */
    canonicalURL?: string | null;
    robots?: {
      noIndex?: boolean | null;
      noFollow?: boolean | null;
    };
    social?: {
      ogTitle?: string | null;
      ogDescription?: string | null;
      ogImage?: (number | null) | Media;
      twitterTitle?: string | null;
      twitterDescription?: string | null;
      twitterImage?: (number | null) | Media;
      twitterCard?: ('summary_large_image' | 'summary') | null;
    };
    schema?: {
      schemaType?:
        ('WebPage' | 'Article' | 'BlogPosting' | 'Service' | 'FAQPage' | 'MedicalOrganization' | 'Physician') | null;
      /**
       * Optional custom JSON-LD schema.
       */
      customSchema?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    /**
     * Comma separated keywords.
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding-page".
 */
export interface BrandingPage {
  id: number;
  brandHero?: {
    brandHeroBadgeLabel?: string | null;
    brandHeroTitleLine1?: string | null;
    brandHeroTitleHighlight?: string | null;
    brandHeroDescription?: string | null;
    brandHeroCtaLabel?: string | null;
    brandHeroCtaLink?: string | null;
    brandHeroImage?: (number | null) | Media;
  };
  brandShowcase?: {
    showcaseSideImage?: (number | null) | Media;
    showcaseHeading?: string | null;
    showcaseDescription?: string | null;
    showcaseImageOne?: (number | null) | Media;
    showcaseImageTwo?: (number | null) | Media;
  };
  brandServices?: {
    brandServicesHeading?: string | null;
    brandServicesDescription?: string | null;
    brandServiceItems?:
      | {
          bsTitle: string;
          bsIcon?: ('BadgeCheck' | 'Palette' | 'MessageSquare' | 'BookOpen' | 'RefreshCw' | 'LayoutGrid') | null;
          bsDescription: string;
          id?: string | null;
        }[]
      | null;
  };
  brandProcess?: {
    processHeading?: string | null;
    processSubheading?: string | null;
    processStepsList?:
      | {
          bpTitle: string;
          bpDescription: string;
          bpIcon?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  brandStats?: {
    statsHeading?: string | null;
    statsDescription?: string | null;
    statsItems?:
      | {
          bStatValue: string;
          bStatLabel: string;
          id?: string | null;
        }[]
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Override canonical URL if needed.
     */
    canonicalURL?: string | null;
    robots?: {
      noIndex?: boolean | null;
      noFollow?: boolean | null;
    };
    social?: {
      ogTitle?: string | null;
      ogDescription?: string | null;
      ogImage?: (number | null) | Media;
      twitterTitle?: string | null;
      twitterDescription?: string | null;
      twitterImage?: (number | null) | Media;
      twitterCard?: ('summary_large_image' | 'summary') | null;
    };
    schema?: {
      schemaType?:
        ('WebPage' | 'Article' | 'BlogPosting' | 'Service' | 'FAQPage' | 'MedicalOrganization' | 'Physician') | null;
      /**
       * Optional custom JSON-LD schema.
       */
      customSchema?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    /**
     * Comma separated keywords.
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar".
 */
export interface Navbar {
  id: number;
  logo?: (number | null) | Media;
  navLinks?:
    | {
        navLabel: string;
        navHref: string;
        id?: string | null;
      }[]
    | null;
  contactCtaLabel?: string | null;
  contactCtaLink?: string | null;
  servicesMenu?: {
    highlightTitle?: string | null;
    highlightDescription?: string | null;
    highlightLink?: string | null;
    highlightCtaLabel?: string | null;
    serviceMenuItems?:
      | {
          smTitle: string;
          smDesc: string;
          smHref: string;
          smIcon?: ('PenTool' | 'Code2' | 'Smartphone' | 'Sparkles' | 'Megaphone' | 'Search' | 'ShoppingCart') | null;
          id?: string | null;
        }[]
      | null;
  };
  industriesMenu?: {
    industriesMenuItems?:
      | {
          imTitle: string;
          imDesc: string;
          imHref: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo?: (number | null) | Media;
  newsletter?: {
    title?: string | null;
    placeholder?: string | null;
    buttonLabel?: string | null;
  };
  companyLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  contact?: {
    workingHours?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
  };
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vision-cta".
 */
export interface VisionCta {
  id: number;
  heading: string;
  buttonLabel?: string | null;
  buttonLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-form".
 */
export interface ContactForm {
  id: number;
  showForm?: boolean | null;
  heading: string;
  submitButtonLabel: string;
  successMessage?: string | null;
  firstName?: {
    placeholder?: string | null;
    requiredMessage?: string | null;
  };
  lastName?: {
    placeholder?: string | null;
    requiredMessage?: string | null;
  };
  email?: {
    placeholder?: string | null;
    requiredMessage?: string | null;
    invalidMessage?: string | null;
  };
  phone?: {
    placeholder?: string | null;
    requiredMessage?: string | null;
    invalidMessage?: string | null;
  };
  message?: {
    placeholder?: string | null;
    requiredMessage?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  hero?: {
    badgeLabel?: string | null;
    titleLine1?: string | null;
    titleHighlight?: string | null;
    description?: string | null;
  };
  formPanel?: {
    panelImage?: (number | null) | Media;
    panelEyebrow?: string | null;
    panelTitleLine1?: string | null;
    panelTitleHighlight?: string | null;
    panelDescription?: string | null;
  };
  contactCards?:
    | {
        ccTitle: string;
        ccValue: string;
        ccIcon?: ('Phone' | 'Send' | 'MapPin') | null;
        id?: string | null;
      }[]
    | null;
  process?: {
    processEyebrow?: string | null;
    processHeading?: string | null;
    processSteps?:
      | {
          psTitle: string;
          psIcon?: ('Video' | 'PhoneCall' | 'TrendingUp') | null;
          psDescription: string;
          id?: string | null;
        }[]
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Override canonical URL if needed.
     */
    canonicalURL?: string | null;
    robots?: {
      noIndex?: boolean | null;
      noFollow?: boolean | null;
    };
    social?: {
      ogTitle?: string | null;
      ogDescription?: string | null;
      ogImage?: (number | null) | Media;
      twitterTitle?: string | null;
      twitterDescription?: string | null;
      twitterImage?: (number | null) | Media;
      twitterCard?: ('summary_large_image' | 'summary') | null;
    };
    schema?: {
      schemaType?:
        ('WebPage' | 'Article' | 'BlogPosting' | 'Service' | 'FAQPage' | 'MedicalOrganization' | 'Physician') | null;
      /**
       * Optional custom JSON-LD schema.
       */
      customSchema?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    /**
     * Comma separated keywords.
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  blogHero?: {
    blogBadgeLabel?: string | null;
    blogTitleLine1?: string | null;
    blogTitleHighlight?: string | null;
    blogHeroImage?: (number | null) | Media;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Override canonical URL if needed.
     */
    canonicalURL?: string | null;
    robots?: {
      noIndex?: boolean | null;
      noFollow?: boolean | null;
    };
    social?: {
      ogTitle?: string | null;
      ogDescription?: string | null;
      ogImage?: (number | null) | Media;
      twitterTitle?: string | null;
      twitterDescription?: string | null;
      twitterImage?: (number | null) | Media;
      twitterCard?: ('summary_large_image' | 'summary') | null;
    };
    schema?: {
      schemaType?:
        ('WebPage' | 'Article' | 'BlogPosting' | 'Service' | 'FAQPage' | 'MedicalOrganization' | 'Physician') | null;
      /**
       * Optional custom JSON-LD schema.
       */
      customSchema?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    /**
     * Comma separated keywords.
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heroTitleLine1?: T;
        heroTitleHighlight?: T;
        heroCtaLabel?: T;
        heroCtaLink?: T;
        heroBackgroundImage?: T;
        heroForegroundImage?: T;
      };
  about?:
    | T
    | {
        aboutHeading?: T;
        aboutHighlightText?: T;
        aboutBodyText?: T;
      };
  stats?:
    | T
    | {
        statValue?: T;
        statLabel?: T;
        id?: T;
      };
  clients?:
    | T
    | {
        clientsHeading?: T;
        clientLogos?:
          | T
          | {
              clientName?: T;
              clientLogo?: T;
              id?: T;
            };
      };
  successStories?:
    | T
    | {
        successHeading?: T;
        successViewMoreLabel?: T;
        successCtaLabel?: T;
        successCtaLink?: T;
        projects?:
          | T
          | {
              projectTitle?: T;
              projectCategory?: T;
              projectImage?: T;
              projectLarge?: T;
              id?: T;
            };
      };
  services?:
    | T
    | {
        servicesHeading?: T;
        serviceItems?:
          | T
          | {
              serviceTitle?: T;
              serviceDescription?: T;
              serviceImage?: T;
              id?: T;
            };
      };
  process?:
    | T
    | {
        processHeading?: T;
        processSteps?:
          | T
          | {
              stepTitle?: T;
              stepDescription?: T;
              stepIcon?: T;
              id?: T;
            };
      };
  technologies?:
    | T
    | {
        techHeading?: T;
        techDescription?: T;
        techCtaHeading?: T;
        techCtaLabel?: T;
        techCtaLink?: T;
        techIcons?:
          | T
          | {
              techName?: T;
              techLogo?: T;
              techX?: T;
              techY?: T;
              techSize?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        testimonialsHeading1?: T;
        testimonialsHeading2?: T;
        testimonialItems?:
          | T
          | {
              testimonialName?: T;
              testimonialReview?: T;
              testimonialRating?: T;
              testimonialAvatar?: T;
              id?: T;
            };
      };
  industries?:
    | T
    | {
        industriesHeading?: T;
        industriesDescription?: T;
        industryItems?:
          | T
          | {
              industryTitle?: T;
              industryDescription?: T;
              industryIcon?: T;
              id?: T;
            };
      };
  latestInsights?:
    | T
    | {
        insightsHeading?: T;
        insightsCtaLabel?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        robots?:
          | T
          | {
              noIndex?: T;
              noFollow?: T;
            };
        social?:
          | T
          | {
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              twitterTitle?: T;
              twitterDescription?: T;
              twitterImage?: T;
              twitterCard?: T;
            };
        schema?:
          | T
          | {
              schemaType?: T;
              customSchema?: T;
            };
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "automotive-page_select".
 */
export interface AutomotivePageSelect<T extends boolean = true> {
  autoHero?:
    | T
    | {
        autoHeroBadgeLabel?: T;
        autoHeroTitleLine1?: T;
        autoHeroTitleHighlight?: T;
        autoHeroDescription?: T;
        autoHeroCtaLabel?: T;
        autoHeroCtaLink?: T;
        autoHeroImage?: T;
        autoHeroStats?:
          | T
          | {
              autoStatValue?: T;
              autoStatLabel?: T;
              id?: T;
            };
      };
  autoSolutions?:
    | T
    | {
        autoSolutionsTitle?: T;
        autoSolutionsHighlight?: T;
        autoSolutionsItems?:
          | T
          | {
              autoSolutionNumber?: T;
              autoSolutionTitle?: T;
              autoSolutionDescription?: T;
              autoSolutionFeatures?:
                | T
                | {
                    featureText?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  autoWhyChooseUs?:
    | T
    | {
        autoWhyTitle?: T;
        autoWhyItems?:
          | T
          | {
              whyTitle?: T;
              whyIcon?: T;
              whyDescription?: T;
              id?: T;
            };
      };
  autoFaq?:
    | T
    | {
        autoFaqHeading?: T;
        autoFaqItems?:
          | T
          | {
              faqQuestion?: T;
              faqAnswer?: T;
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        robots?:
          | T
          | {
              noIndex?: T;
              noFollow?: T;
            };
        social?:
          | T
          | {
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              twitterTitle?: T;
              twitterDescription?: T;
              twitterImage?: T;
              twitterCard?: T;
            };
        schema?:
          | T
          | {
              schemaType?: T;
              customSchema?: T;
            };
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding-page_select".
 */
export interface BrandingPageSelect<T extends boolean = true> {
  brandHero?:
    | T
    | {
        brandHeroBadgeLabel?: T;
        brandHeroTitleLine1?: T;
        brandHeroTitleHighlight?: T;
        brandHeroDescription?: T;
        brandHeroCtaLabel?: T;
        brandHeroCtaLink?: T;
        brandHeroImage?: T;
      };
  brandShowcase?:
    | T
    | {
        showcaseSideImage?: T;
        showcaseHeading?: T;
        showcaseDescription?: T;
        showcaseImageOne?: T;
        showcaseImageTwo?: T;
      };
  brandServices?:
    | T
    | {
        brandServicesHeading?: T;
        brandServicesDescription?: T;
        brandServiceItems?:
          | T
          | {
              bsTitle?: T;
              bsIcon?: T;
              bsDescription?: T;
              id?: T;
            };
      };
  brandProcess?:
    | T
    | {
        processHeading?: T;
        processSubheading?: T;
        processStepsList?:
          | T
          | {
              bpTitle?: T;
              bpDescription?: T;
              bpIcon?: T;
              id?: T;
            };
      };
  brandStats?:
    | T
    | {
        statsHeading?: T;
        statsDescription?: T;
        statsItems?:
          | T
          | {
              bStatValue?: T;
              bStatLabel?: T;
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        robots?:
          | T
          | {
              noIndex?: T;
              noFollow?: T;
            };
        social?:
          | T
          | {
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              twitterTitle?: T;
              twitterDescription?: T;
              twitterImage?: T;
              twitterCard?: T;
            };
        schema?:
          | T
          | {
              schemaType?: T;
              customSchema?: T;
            };
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar_select".
 */
export interface NavbarSelect<T extends boolean = true> {
  logo?: T;
  navLinks?:
    | T
    | {
        navLabel?: T;
        navHref?: T;
        id?: T;
      };
  contactCtaLabel?: T;
  contactCtaLink?: T;
  servicesMenu?:
    | T
    | {
        highlightTitle?: T;
        highlightDescription?: T;
        highlightLink?: T;
        highlightCtaLabel?: T;
        serviceMenuItems?:
          | T
          | {
              smTitle?: T;
              smDesc?: T;
              smHref?: T;
              smIcon?: T;
              id?: T;
            };
      };
  industriesMenu?:
    | T
    | {
        industriesMenuItems?:
          | T
          | {
              imTitle?: T;
              imDesc?: T;
              imHref?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  newsletter?:
    | T
    | {
        title?: T;
        placeholder?: T;
        buttonLabel?: T;
      };
  companyLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        workingHours?: T;
        phone?: T;
        email?: T;
      };
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vision-cta_select".
 */
export interface VisionCtaSelect<T extends boolean = true> {
  heading?: T;
  buttonLabel?: T;
  buttonLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-form_select".
 */
export interface ContactFormSelect<T extends boolean = true> {
  showForm?: T;
  heading?: T;
  submitButtonLabel?: T;
  successMessage?: T;
  firstName?:
    | T
    | {
        placeholder?: T;
        requiredMessage?: T;
      };
  lastName?:
    | T
    | {
        placeholder?: T;
        requiredMessage?: T;
      };
  email?:
    | T
    | {
        placeholder?: T;
        requiredMessage?: T;
        invalidMessage?: T;
      };
  phone?:
    | T
    | {
        placeholder?: T;
        requiredMessage?: T;
        invalidMessage?: T;
      };
  message?:
    | T
    | {
        placeholder?: T;
        requiredMessage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badgeLabel?: T;
        titleLine1?: T;
        titleHighlight?: T;
        description?: T;
      };
  formPanel?:
    | T
    | {
        panelImage?: T;
        panelEyebrow?: T;
        panelTitleLine1?: T;
        panelTitleHighlight?: T;
        panelDescription?: T;
      };
  contactCards?:
    | T
    | {
        ccTitle?: T;
        ccValue?: T;
        ccIcon?: T;
        id?: T;
      };
  process?:
    | T
    | {
        processEyebrow?: T;
        processHeading?: T;
        processSteps?:
          | T
          | {
              psTitle?: T;
              psIcon?: T;
              psDescription?: T;
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        robots?:
          | T
          | {
              noIndex?: T;
              noFollow?: T;
            };
        social?:
          | T
          | {
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              twitterTitle?: T;
              twitterDescription?: T;
              twitterImage?: T;
              twitterCard?: T;
            };
        schema?:
          | T
          | {
              schemaType?: T;
              customSchema?: T;
            };
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  blogHero?:
    | T
    | {
        blogBadgeLabel?: T;
        blogTitleLine1?: T;
        blogTitleHighlight?: T;
        blogHeroImage?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        robots?:
          | T
          | {
              noIndex?: T;
              noFollow?: T;
            };
        social?:
          | T
          | {
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              twitterTitle?: T;
              twitterDescription?: T;
              twitterImage?: T;
              twitterCard?: T;
            };
        schema?:
          | T
          | {
              schemaType?: T;
              customSchema?: T;
            };
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}